name: Like Bluesky Bot

on:
  schedule:
    - cron: '30 * * * *'  # 毎時15分に実行（重複しないように）
  workflow_dispatch:  # 手動実行もOK

jobs:
  run-like-bot:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 依存関係インストール
        run: |
          python -m pip install --upgrade pip
          pip install atproto python-dotenv

      - name: 環境変数の設定
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: LikeBotを実行
        run: python like_bot.py
        env:
          HANDLE: ${{ secrets.HANDLE }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        
