name: Mirin Magic Bot

on:
  schedule:
    - cron: '0 5 * * *'   # JST 14:00 (UTC 5:00)
    - cron: '0 13 * * *'  # JST 22:00 (UTC 13:00)
  workflow_dispatch:  # 手動実行もできるように

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          HANDLE: ${{ secrets.HANDLE }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}  # HuggingFace使う場合
        run: python MirinMagicBot.py