name: Bluesky Reply Bot

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

concurrency:
  group: bluesky-reply
  cancel-in-progress: false

jobs:
  run-reply-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clear HuggingFace cache
        run: |
          rm -rf ~/.cache/huggingface

      - name: Clear pip cache
        run: |
          pip cache purge

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install torch==2.0.1 transformers==4.38.2 psutil==5.9.8 sentencepiece==0.2.0
          pip install -U accelerate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check installed packages
        run: pip list

      - name: Check GPU
        run: |
          if command -v nvidia-smi; then nvidia-smi; else echo "No GPU detected"; fi

      - name: Run Reply Bot
        env:
          HANDLE: ${{ secrets.HANDLE }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          REPLIED_JSON_URL: ${{ secrets.REPLIED_JSON_URL }}
          GIST_TOKEN_REPLY: ${{ secrets.GIST_TOKEN_REPLY }}
          GIST_ID: 40391085a2e0b8a48935ad0b460cf422
        run: |
          python reply_bot.py