name: Bluesky Reply Bot

on:
  schedule:
    - cron: "*/30 * * * *"  # 30分ごとに実行
  workflow_dispatch:
concurrency:
  group: bluesky-reply
  cancel-in-progress: false
jobs:
  run-reply-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Reply Bot
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
          GIST_TOKEN_REPLY: ${{ secrets.GIST_TOKEN_REPLY }}
          GIST_ID: 40391085a2e0b8a48935ad0b460cf422
        run: python reply_bot.py