name: Bluesky Reply 

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

concurrency:
  group: bluesky-reply
  cancel-in-progress: false

jobs:
  run-reply-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clear HuggingFace cache
        run: rm -rf ~/.cache/huggingface

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch==2.0.1
          pip install pytz
          pip install transformers==4.39.3 accelerate sentencepiece psutil
          pip install groq
          pip install huggingface_hub  # ★画像生成: Hugging Face API用

      - name: Run Reply Bot with Groq
        env:
          HANDLE: ${{ secrets.HANDLE }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GIST_TOKEN_REPLY: ${{ secrets.GIST_TOKEN_REPLY }}
          GIST_ID: 40391085a2e0b8a48935ad0b460cf422
          HF_TOKEN: ${{ secrets.HF_TOKEN }}  # ★画像生成: Hugging Face APIキー
        run: |
          python reply_bot.py