name: Seasonal Note Bot
on:
  schedule:
    - cron: "0 11 5 * *"  # 毎月5日20:00 JST (UTC+9 = 11:00 UTC)
  workflow_dispatch:  # 手動実行もできるように
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install atproto apscheduler pyyaml
      - name: Run bot
        env:
          HANDLE: ${{ secrets.HANDLE }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: python seasonal_notes.py